/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.qlth.frm;

import com.qlth.dao.AnhBiaSachDAO;
import com.qlth.dao.HangHoaDAO;
import com.qlth.dao.HoaDonDAO;
import com.qlth.dao.KhoDAO;
import com.qlth.dao.NhatKyBanSachDAO;
import com.qlth.obj.GioHang;
import com.qlth.obj.HangHoa;
import com.qlth.obj.HoaDon;
import com.qlth.obj.Kho;
import com.qlth.obj.NhatKyBanSach;
import com.qlth.util.Convert;
import java.awt.ComponentOrientation;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hong Hiep
 */
public class FrmBanHang extends javax.swing.JFrame {

    ArrayList<HangHoa> ttHH = new ArrayList<HangHoa>();
    DefaultTableModel tableModel = new DefaultTableModel();

    /**
     * Creates new form FrmBanHang
     */
    public FrmBanHang() {
        initComponents();
        loadDuLieuLenLuoi();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        pnThanhToan.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel9 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txtTimKiem = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnTimKiem = new javax.swing.JButton();
        btnResetBang = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        lblBiaSach = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDanhMucSach = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblSoLuongHangCon = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtSoLuongKhachMua = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnThemVaoGioHang = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblGioHang = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        btnBoSanPham = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lblTongTien = new javax.swing.JLabel();
        btnHuyHoaDon = new javax.swing.JButton();
        btnTinhTien = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        pnThanhToan = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtTienKhachDua = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        btnNamMuoiNghin = new javax.swing.JButton();
        btnMotTramNghin = new javax.swing.JButton();
        btnHaiTramNghin = new javax.swing.JButton();
        btnNamTramNghin = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btnXoaLui = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btnXoaTrang = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtTienTraLaiKhach = new javax.swing.JTextField();
        btnThanhToan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder("Chức năng"));

        jPanel1.setLayout(new java.awt.GridLayout(2, 1));
        jPanel1.add(txtTimKiem);

        jLabel1.setText("(*)Tìm kiếm theo danh sách");
        jPanel1.add(jLabel1);

        jPanel2.setLayout(new java.awt.GridLayout(2, 1));

        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlth/img/26.png"))); // NOI18N
        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });
        jPanel2.add(btnTimKiem);

        btnResetBang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlth/img/27.png"))); // NOI18N
        btnResetBang.setText("Reset bảng");
        btnResetBang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetBangActionPerformed(evt);
            }
        });
        jPanel2.add(btnResetBang);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder("Bìa sách"));
        jPanel12.setLayout(new java.awt.GridLayout(1, 1));
        jPanel12.add(lblBiaSach);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh mục sách"));
        jPanel3.setLayout(new java.awt.GridLayout(1, 1));

        tblDanhMucSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDanhMucSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDanhMucSachMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDanhMucSach);

        jPanel3.add(jScrollPane1);

        jPanel4.setLayout(new java.awt.GridLayout(3, 2));

        jLabel2.setText("Số lượng hàng còn");
        jPanel4.add(jLabel2);
        jPanel4.add(lblSoLuongHangCon);

        jLabel3.setText("Số lượng khách mua");
        jPanel4.add(jLabel3);
        jPanel4.add(txtSoLuongKhachMua);
        jPanel4.add(jLabel4);

        btnThemVaoGioHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlth/img/50.png"))); // NOI18N
        btnThemVaoGioHang.setText("Thêm vào giỏ hàng");
        btnThemVaoGioHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemVaoGioHangActionPerformed(evt);
            }
        });
        jPanel4.add(btnThemVaoGioHang);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(202, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Giỏ hàng"));
        jPanel5.setLayout(new java.awt.GridLayout(1, 1));

        tblGioHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblGioHang);

        jPanel5.add(jScrollPane2);

        jPanel6.setLayout(new java.awt.GridLayout(2, 3));

        btnBoSanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlth/img/53.png"))); // NOI18N
        btnBoSanPham.setText("Bỏ sản phẩm");
        btnBoSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBoSanPhamActionPerformed(evt);
            }
        });
        jPanel6.add(btnBoSanPham);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Tổng tiền:");
        jPanel6.add(jLabel5);
        jPanel6.add(lblTongTien);

        btnHuyHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlth/img/52.png"))); // NOI18N
        btnHuyHoaDon.setText("Hủy hóa đơn");
        btnHuyHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyHoaDonActionPerformed(evt);
            }
        });
        jPanel6.add(btnHuyHoaDon);

        btnTinhTien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlth/img/54.png"))); // NOI18N
        btnTinhTien.setText("Tính tiền");
        btnTinhTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTinhTienActionPerformed(evt);
            }
        });
        jPanel6.add(btnTinhTien);
        jPanel6.add(jLabel6);

        pnThanhToan.setBorder(javax.swing.BorderFactory.createTitledBorder("Thanh toán"));

        jLabel7.setText("Tiền khách đưa");

        txtTienKhachDua.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jPanel8.setLayout(new java.awt.GridLayout(4, 4));

        btnNamMuoiNghin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlth/img/58.png"))); // NOI18N
        btnNamMuoiNghin.setText("50000 VNĐ");
        btnNamMuoiNghin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNamMuoiNghinActionPerformed(evt);
            }
        });
        jPanel8.add(btnNamMuoiNghin);

        btnMotTramNghin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlth/img/58.png"))); // NOI18N
        btnMotTramNghin.setText("100000 VNĐ");
        btnMotTramNghin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMotTramNghinActionPerformed(evt);
            }
        });
        jPanel8.add(btnMotTramNghin);

        btnHaiTramNghin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlth/img/58.png"))); // NOI18N
        btnHaiTramNghin.setText("200000 VNĐ");
        btnHaiTramNghin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHaiTramNghinActionPerformed(evt);
            }
        });
        jPanel8.add(btnHaiTramNghin);

        btnNamTramNghin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlth/img/58.png"))); // NOI18N
        btnNamTramNghin.setText("500000 VNĐ");
        btnNamTramNghin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNamTramNghinActionPerformed(evt);
            }
        });
        jPanel8.add(btnNamTramNghin);

        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jPanel8.add(btn1);

        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        jPanel8.add(btn2);

        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        jPanel8.add(btn3);

        btn0.setText("0");
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });
        jPanel8.add(btn0);

        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        jPanel8.add(btn4);

        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        jPanel8.add(btn5);

        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        jPanel8.add(btn6);

        btnXoaLui.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlth/img/56.png"))); // NOI18N
        btnXoaLui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaLuiActionPerformed(evt);
            }
        });
        jPanel8.add(btnXoaLui);

        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        jPanel8.add(btn7);

        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        jPanel8.add(btn8);

        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        jPanel8.add(btn9);

        btnXoaTrang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlth/img/57.png"))); // NOI18N
        btnXoaTrang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaTrangActionPerformed(evt);
            }
        });
        jPanel8.add(btnXoaTrang);

        jLabel8.setText("Tiền trả lại khách");

        txtTienTraLaiKhach.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnThanhToan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlth/img/55.png"))); // NOI18N
        btnThanhToan.setText("Thanh toán");
        btnThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhToanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnThanhToanLayout = new javax.swing.GroupLayout(pnThanhToan);
        pnThanhToan.setLayout(pnThanhToanLayout);
        pnThanhToanLayout.setHorizontalGroup(
            pnThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnThanhToanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnThanhToanLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(txtTienKhachDua, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnThanhToanLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTienTraLaiKhach)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnThanhToanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
        );
        pnThanhToanLayout.setVerticalGroup(
            pnThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThanhToanLayout.createSequentialGroup()
                .addGroup(pnThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnThanhToanLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel7))
                    .addGroup(pnThanhToanLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtTienKhachDua, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtTienTraLaiKhach, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnThanhToan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnThanhToan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        pnThanhToan.setVisible(false);

        tableModel = new DefaultTableModel();
        //tạo cột
        tableModel.addColumn("Mã sách");
        tableModel.addColumn("Tên sách");
        tableModel.addColumn("Tác giả");
        tableModel.addColumn("Nhà xuất bản");
        tableModel.addColumn("Giá mua");
        tableModel.addColumn("Số lượng");

        HangHoaDAO hangHoaDAO = new HangHoaDAO();
        //lấy ra thông tin tìm kiếm
        HangHoa hh = new HangHoa();
        hh.setMaSach(txtTimKiem.getText());
        hh.setTenSach(txtTimKiem.getText());

        List<HangHoa> hangHoaList = hangHoaDAO.search(hh);
        for (HangHoa hangHoa : hangHoaList) {
            Vector vector = new Vector();
            vector.add(hangHoa.getMaSach());
            vector.add(hangHoa.getTenSach());
            vector.add(hangHoa.getTacGia());
            vector.add(hangHoa.getNhaXuatBan());
            vector.add(hangHoa.getGiaMua());
            vector.add(hangHoa.getSoLuong());

            //tạo hàng
            tableModel.addRow(vector);
        }
        //đưa dữ liệu từ model vào bảng
        tblDanhMucSach.setModel(tableModel);
        tblDanhMucSach.getColumnModel().getColumn(1).setPreferredWidth(150);
        tblDanhMucSach.getColumnModel().getColumn(2).setPreferredWidth(150);
        tblDanhMucSach.getColumnModel().getColumn(3).setPreferredWidth(150);
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnResetBangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetBangActionPerformed
        pnThanhToan.setVisible(false);
        loadDuLieuLenLuoi();
    }//GEN-LAST:event_btnResetBangActionPerformed

    private void tblDanhMucSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhMucSachMouseClicked
        pnThanhToan.setVisible(false);

        int row = tblDanhMucSach.getSelectedRow();

        String maSach = (String) tblDanhMucSach.getValueAt(row, 0);

        String tenSach = (String) tblDanhMucSach.getValueAt(row, 1);

        String tenTacGia = (String) tblDanhMucSach.getValueAt(row, 2);

        String tenNhaCungCap = (String) tblDanhMucSach.getValueAt(row, 3);

        Integer giaMua = Integer.parseInt(tblDanhMucSach.getValueAt(row, 4).toString());

        Integer soLuong = Integer.parseInt(tblDanhMucSach.getValueAt(row, 5).toString());

//        for (SanPham2 data : ttSP) {
//            data.getMaSanPham().contains(maSanPham);
//        }
        Integer soLuongMua = 0;
        for (int i = 0; i < ttHH.size(); i++) {
            if (ttHH.get(i).getMaSach().contains(maSach)) {
                soLuongMua = ttHH.get(i).getSoLuong();
            }
        }
        Integer soLuongCon = (soLuong - soLuongMua);
        lblSoLuongHangCon.setText(soLuongCon.toString());
        setImage(maSach);
    }//GEN-LAST:event_tblDanhMucSachMouseClicked

    private void btnThemVaoGioHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemVaoGioHangActionPerformed
        pnThanhToan.setVisible(false);

        int row = tblDanhMucSach.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn sản phẩm");
            return;
        }

        String maSach = (String) tblDanhMucSach.getValueAt(row, 0);

        String tenSach = (String) tblDanhMucSach.getValueAt(row, 1);

        String tenTacGia = (String) tblDanhMucSach.getValueAt(row, 2);

        String tenNhaCungCap = (String) tblDanhMucSach.getValueAt(row, 3);

        Integer giaMua = Integer.parseInt(tblDanhMucSach.getValueAt(row, 4).toString());

        Integer soLuong = Integer.parseInt(tblDanhMucSach.getValueAt(row, 5).toString());

        Integer soLuongMua = null;
        Integer soLuongCon = null;

        if (txtSoLuongKhachMua.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Bạn chưa điền số hàng muốn mua");
            return;
        }
        try {
            soLuongMua = Integer.parseInt(txtSoLuongKhachMua.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Điền không hợp lệ");
            return;
        }
        if (soLuongMua <= 0) {
            JOptionPane.showMessageDialog(this, "Điền không hợp lệ");
            return;
        }

        if (soLuongMua <= Integer.parseInt(lblSoLuongHangCon.getText())) {
            boolean check = false;
            for (int i = 0; i < ttHH.size(); i++) {
                if (ttHH.get(i).getMaSach().contains(maSach)) {

                    soLuongCon = soLuong - (ttHH.get(i).getSoLuong() + soLuongMua);
                    ttHH.get(i).setSoLuongCon(soLuongCon);
                    ttHH.get(i).setSoLuong(ttHH.get(i).getSoLuong() + soLuongMua);
                    check = true;
                    tableModel = new DefaultTableModel();
                    //tạo cột
                    tableModel.addColumn("Mã Sách");
                    tableModel.addColumn("Tên sách");
//                    tableModel.addColumn("Tác giả");
//                    tableModel.addColumn("Nhà xuất bản");
                    tableModel.addColumn("Giá");
                    tableModel.addColumn("Số lượng");

                    for (HangHoa data : ttHH) {
                        Vector vector = new Vector();
                        vector.add(data.getMaSach());
                        vector.add(data.getTenSach());
//                        vector.add(data.getTacGia());
//                        vector.add(data.getNhaXuatBan());
                        vector.add(data.getGiaMua());
                        vector.add(data.getSoLuong());

                        //tạo hàng
                        tableModel.addRow(vector);
                    }
                    tblGioHang.setModel(tableModel);
                    tblGioHang.getColumnModel().getColumn(1).setPreferredWidth(200);
                }
            }
            if (!check) {
                soLuongCon = soLuong - soLuongMua;

                HangHoa hh = new HangHoa();
                hh.setMaSach(maSach);
                hh.setTenSach(tenSach);
                hh.setTacGia(tenTacGia);
                hh.setNhaXuatBan(tenNhaCungCap);
                hh.setGiaMua(giaMua);
                hh.setSoLuong(soLuongMua);
                hh.setSoLuongCon(soLuongCon);

                ttHH.add(hh);

                tableModel = new DefaultTableModel();
                //tạo cột
                tableModel.addColumn("Mã Sách");
                tableModel.addColumn("Tên sách");
//                tableModel.addColumn("Tác giả");
//                tableModel.addColumn("Nhà xuất bản");
                tableModel.addColumn("Giá");
                tableModel.addColumn("Số lượng");
                for (HangHoa data : ttHH) {
                    Vector vector = new Vector();
                    vector.add(data.getMaSach());
                    vector.add(data.getTenSach());
//                    vector.add(data.getTacGia());
//                    vector.add(data.getNhaXuatBan());
                    vector.add(data.getGiaMua());
                    vector.add(data.getSoLuong());

                    //tạo hàng
                    tableModel.addRow(vector);
                }
                tblGioHang.setModel(tableModel);
                tblGioHang.getColumnModel().getColumn(1).setPreferredWidth(200);
            }
            lblSoLuongHangCon.setText(soLuongCon.toString());
            tinhTongTien();
        } else {
            JOptionPane.showMessageDialog(this, "Không đủ hàng trong kho");
        }

    }//GEN-LAST:event_btnThemVaoGioHangActionPerformed

    private void btnBoSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBoSanPhamActionPerformed
        pnThanhToan.setVisible(false);

        int row = tblGioHang.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn sản phẩm muốn bỏ");
            return;
        }

        String maSach = (String) tblGioHang.getValueAt(row, 0);

        String tenSach = (String) tblGioHang.getValueAt(row, 1);

        Integer giaMua = Integer.parseInt(tblGioHang.getValueAt(row, 2).toString());

        Integer soLuong = Integer.parseInt(tblGioHang.getValueAt(row, 3).toString());

        for (int i = 0; i < ttHH.size(); i++) {
            if (ttHH.get(i).getMaSach().contains(maSach)) {
                ttHH.remove(i);
            }
        }
        tinhTongTien();
        tableModel = new DefaultTableModel();
        //tạo cột
        tableModel.addColumn("Mã sách");
        tableModel.addColumn("Tên sách");
        tableModel.addColumn("Giá mua");
        tableModel.addColumn("Số lượng");

        for (HangHoa data : ttHH) {
            Vector vector = new Vector();
            vector.add(data.getMaSach());
            vector.add(data.getTenSach());
            vector.add(data.getGiaMua());
            vector.add(data.getSoLuong());

            //tạo hàng
            tableModel.addRow(vector);
        }
        tblGioHang.setModel(tableModel);
        tblGioHang.getColumnModel().getColumn(1).setPreferredWidth(200);
    }//GEN-LAST:event_btnBoSanPhamActionPerformed

    private void btnHuyHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyHoaDonActionPerformed
        pnThanhToan.setVisible(false);

        ttHH.removeAll(ttHH);
        tableModel = new DefaultTableModel();
        //tạo cột
        tableModel.addColumn("Mã sách");
        tableModel.addColumn("Tên sách");
        tableModel.addColumn("Giá mua");
        tableModel.addColumn("Số lượng");

        for (HangHoa data : ttHH) {
            Vector vector = new Vector();
            vector.add(data.getMaSach());
            vector.add(data.getTenSach());
            vector.add(data.getGiaMua());
            vector.add(data.getSoLuong());

            //tạo hàng
            tableModel.addRow(vector);
        }
        tblGioHang.setModel(tableModel);
        tinhTongTien();
    }//GEN-LAST:event_btnHuyHoaDonActionPerformed

    private void btnTinhTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTinhTienActionPerformed
        if (lblTongTien.getText().equals("")) {
            return;
        } else {
            pnThanhToan.setVisible(true);
            txtTienKhachDua.setEditable(false);
            txtTienTraLaiKhach.setEditable(false);
            setTrueButton();
            Integer tongTien = Integer.parseInt(lblTongTien.getText());
            if (tongTien > 500000) {
                btnNamTramNghin.setEnabled(false);
                btnHaiTramNghin.setEnabled(false);
                btnMotTramNghin.setEnabled(false);
                btnNamMuoiNghin.setEnabled(false);
            } else if (tongTien > 200000) {
                btnHaiTramNghin.setEnabled(false);
                btnMotTramNghin.setEnabled(false);
                btnNamMuoiNghin.setEnabled(false);
            } else if (tongTien > 100000) {
                btnMotTramNghin.setEnabled(false);
                btnNamMuoiNghin.setEnabled(false);
            } else if (tongTien > 50000) {
                btnNamMuoiNghin.setEnabled(false);
            }
        }
    }//GEN-LAST:event_btnTinhTienActionPerformed

    private void btnNamMuoiNghinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNamMuoiNghinActionPerformed
        txtTienKhachDua.setText("50000");
        setFalseButton();
        tinhTienDu();
    }//GEN-LAST:event_btnNamMuoiNghinActionPerformed

    private void btnMotTramNghinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMotTramNghinActionPerformed
        txtTienKhachDua.setText("100000");
        setFalseButton();
        tinhTienDu();
    }//GEN-LAST:event_btnMotTramNghinActionPerformed

    private void btnHaiTramNghinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHaiTramNghinActionPerformed
        txtTienKhachDua.setText("200000");
        setFalseButton();
        tinhTienDu();
    }//GEN-LAST:event_btnHaiTramNghinActionPerformed

    private void btnNamTramNghinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNamTramNghinActionPerformed
        txtTienKhachDua.setText("500000");
        setFalseButton();
        tinhTienDu();
    }//GEN-LAST:event_btnNamTramNghinActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        if (txtTienKhachDua.getText().length() > 8) {
            return;
        }
        if (txtTienKhachDua.getText().isEmpty()) {
            txtTienKhachDua.setText("1");
        } else {
            String monney = txtTienKhachDua.getText() + "1";
            txtTienKhachDua.setText(monney);
        }
        tinhTienDu();
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        if (txtTienKhachDua.getText().length() > 8) {
            return;
        }
        if (txtTienKhachDua.getText().isEmpty()) {
            txtTienKhachDua.setText("2");
        } else {
            String monney = txtTienKhachDua.getText() + "2";
            txtTienKhachDua.setText(monney);
        }
        tinhTienDu();
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        if (txtTienKhachDua.getText().length() > 8) {
            return;
        }
        if (txtTienKhachDua.getText().isEmpty()) {
            txtTienKhachDua.setText("3");
        } else {
            String monney = txtTienKhachDua.getText() + "3";
            txtTienKhachDua.setText(monney);
        }
        tinhTienDu();
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        if (txtTienKhachDua.getText().length() > 8) {
            return;
        }
        if (txtTienKhachDua.getText().isEmpty()) {
            txtTienKhachDua.setText("");
        } else {
            String monney = txtTienKhachDua.getText() + "0";
            txtTienKhachDua.setText(monney);
        }
        tinhTienDu();
    }//GEN-LAST:event_btn0ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        if (txtTienKhachDua.getText().length() > 8) {
            return;
        }
        if (txtTienKhachDua.getText().isEmpty()) {
            txtTienKhachDua.setText("4");
        } else {
            String monney = txtTienKhachDua.getText() + "4";
            txtTienKhachDua.setText(monney);
        }
        tinhTienDu();
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        if (txtTienKhachDua.getText().length() > 8) {
            return;
        }
        if (txtTienKhachDua.getText().isEmpty()) {
            txtTienKhachDua.setText("5");
        } else {
            String monney = txtTienKhachDua.getText() + "5";
            txtTienKhachDua.setText(monney);
        }
        tinhTienDu();
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        if (txtTienKhachDua.getText().length() > 8) {
            return;
        }
        if (txtTienKhachDua.getText().isEmpty()) {
            txtTienKhachDua.setText("6");
        } else {
            String monney = txtTienKhachDua.getText() + "6";
            txtTienKhachDua.setText(monney);
        }
        tinhTienDu();
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        if (txtTienKhachDua.getText().length() > 8) {
            return;
        }
        if (txtTienKhachDua.getText().isEmpty()) {
            txtTienKhachDua.setText("7");
        } else {
            String monney = txtTienKhachDua.getText() + "7";
            txtTienKhachDua.setText(monney);
        }
        tinhTienDu();
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        if (txtTienKhachDua.getText().length() > 8) {
            return;
        }
        if (txtTienKhachDua.getText().isEmpty()) {
            txtTienKhachDua.setText("8");
        } else {
            String monney = txtTienKhachDua.getText() + "8";
            txtTienKhachDua.setText(monney);
        }
        tinhTienDu();
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        if (txtTienKhachDua.getText().length() > 8) {
            return;
        }
        if (txtTienKhachDua.getText().isEmpty()) {
            txtTienKhachDua.setText("9");
        } else {
            String monney = txtTienKhachDua.getText() + "9";
            txtTienKhachDua.setText(monney);
        }
        tinhTienDu();
    }//GEN-LAST:event_btn9ActionPerformed

    private void btnXoaTrangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaTrangActionPerformed
        txtTienKhachDua.setText("");
        tinhTienDu();
        setTrueButton();
        Integer tongTien = Integer.parseInt(lblTongTien.getText());
        if (tongTien > 500000) {
            btnNamTramNghin.setEnabled(false);
            btnHaiTramNghin.setEnabled(false);
            btnMotTramNghin.setEnabled(false);
            btnNamMuoiNghin.setEnabled(false);
        } else if (tongTien > 200000) {
            btnHaiTramNghin.setEnabled(false);
            btnMotTramNghin.setEnabled(false);
            btnNamMuoiNghin.setEnabled(false);
        } else if (tongTien > 100000) {
            btnMotTramNghin.setEnabled(false);
            btnNamMuoiNghin.setEnabled(false);
        } else if (tongTien > 50000) {
            btnNamMuoiNghin.setEnabled(false);
        }
    }//GEN-LAST:event_btnXoaTrangActionPerformed

    private void btnXoaLuiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaLuiActionPerformed
        if (txtTienKhachDua.getText().isEmpty()) {
            return;
        } else {
            String money = txtTienKhachDua.getText().substring(0, txtTienKhachDua.getText().length() - 1);
            txtTienKhachDua.setText(money);
        }
        tinhTienDu();
    }//GEN-LAST:event_btnXoaLuiActionPerformed

    private void btnThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhToanActionPerformed

        Integer tienKhachDua = Integer.parseInt(txtTienKhachDua.getText());
        Integer tienTraLaiKhach = Integer.parseInt(txtTienTraLaiKhach.getText());
        if (tienTraLaiKhach < 0) {
            JOptionPane.showMessageDialog(this, "chưa đủ tiền thanh toán");
            return;
        }
        for (int i = 0; i < ttHH.size(); i++) {
            KhoDAO khoDAO = new KhoDAO();
            Kho k = new Kho();
            k.setMaSach(ttHH.get(i).getMaSach());
            k.setSoLuong(ttHH.get(i).getSoLuongCon());

            khoDAO.update2(k);
        }

        Integer tongTien = Integer.parseInt(lblTongTien.getText());
        HoaDonDAO hoaDonDAO = new HoaDonDAO();
        HoaDon hoaDon = new HoaDon(new Date(), tongTien, tienKhachDua, tienTraLaiKhach);
        hoaDonDAO.insert(hoaDon);
        
        Integer maHoaDon=hoaDonDAO.getMaHoaDon();

        for (int i = 0; i < ttHH.size(); i++) {
            NhatKyBanSachDAO nhatKyBanSachDAO=new NhatKyBanSachDAO();
            NhatKyBanSach nhatKyBanSach=
                    new NhatKyBanSach(ttHH.get(i).getMaSach(),ttHH.get(i).getSoLuong(), new Date(),maHoaDon);
            nhatKyBanSachDAO.insert(nhatKyBanSach);
        }

        JOptionPane.showMessageDialog(this, "Thanh toán thành công");
        loadDuLieuLenLuoi();
        ttHH.removeAll(ttHH);
        tableModel = new DefaultTableModel();
        //tạo cột
        tableModel.addColumn("Mã sách");
        tableModel.addColumn("Tên sách");
        tableModel.addColumn("Giá mua");
        tableModel.addColumn("Số lượng");

        for (HangHoa data : ttHH) {
            Vector vector = new Vector();
            vector.add(data.getMaSach());
            vector.add(data.getTenSach());
            vector.add(data.getGiaMua());
            vector.add(data.getSoLuong());

            //tạo hàng
            tableModel.addRow(vector);
        }
        tblGioHang.setModel(tableModel);
        tinhTongTien();
        pnThanhToan.setVisible(false);
    }//GEN-LAST:event_btnThanhToanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmBanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmBanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmBanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmBanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmBanHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnBoSanPham;
    private javax.swing.JButton btnHaiTramNghin;
    private javax.swing.JButton btnHuyHoaDon;
    private javax.swing.JButton btnMotTramNghin;
    private javax.swing.JButton btnNamMuoiNghin;
    private javax.swing.JButton btnNamTramNghin;
    private javax.swing.JButton btnResetBang;
    private javax.swing.JButton btnThanhToan;
    private javax.swing.JButton btnThemVaoGioHang;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnTinhTien;
    private javax.swing.JButton btnXoaLui;
    private javax.swing.JButton btnXoaTrang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBiaSach;
    private javax.swing.JLabel lblSoLuongHangCon;
    private javax.swing.JLabel lblTongTien;
    private javax.swing.JPanel pnThanhToan;
    private javax.swing.JTable tblDanhMucSach;
    private javax.swing.JTable tblGioHang;
    private javax.swing.JTextField txtSoLuongKhachMua;
    private javax.swing.JTextField txtTienKhachDua;
    private javax.swing.JTextField txtTienTraLaiKhach;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables

    private void loadDuLieuLenLuoi() {
        tableModel = new DefaultTableModel();
        //tạo cột
        tableModel.addColumn("Mã sách");
        tableModel.addColumn("Tên sách");
        tableModel.addColumn("Tác giả");
        tableModel.addColumn("Nhà xuất bản");
        tableModel.addColumn("Giá mua");
        tableModel.addColumn("Số lượng còn");

        HangHoaDAO hangHoaDAO = new HangHoaDAO();
        //lấy ra toàn bộ vai trò
        List<HangHoa> hangHoaList = hangHoaDAO.selectAll();
        for (HangHoa hangHoa : hangHoaList) {
            Vector vector = new Vector();
            vector.add(hangHoa.getMaSach());
            vector.add(hangHoa.getTenSach());
            vector.add(hangHoa.getTacGia());
            vector.add(hangHoa.getNhaXuatBan());
            vector.add(hangHoa.getGiaMua());
            vector.add(hangHoa.getSoLuong());

            //tạo hàng
            tableModel.addRow(vector);
        }
        //đưa dữ liệu từ model vào bảng
        tblDanhMucSach.setModel(tableModel);
        tblDanhMucSach.getColumnModel().getColumn(1).setPreferredWidth(150);
        tblDanhMucSach.getColumnModel().getColumn(2).setPreferredWidth(150);
        tblDanhMucSach.getColumnModel().getColumn(3).setPreferredWidth(150);
    }

    private void tinhTongTien() {
        Integer tongTien = 0;
        for (int i = 0; i < ttHH.size(); i++) {
            tongTien += ttHH.get(i).getSoLuong() * ttHH.get(i).getGiaMua();
        }
        if (tongTien > 0) {
            lblTongTien.setText(tongTien.toString());
        } else {
            lblTongTien.setText("");
        }
    }

    private void setImage(String maSach) {
        AnhBiaSachDAO anhBiaSachDao = new AnhBiaSachDAO();
        String path = anhBiaSachDao.getImageById(maSach).getPathAnh();
//        lblBiaSach.setIcon(new ImageIcon(path!=null?path:""));
        if (path != null) {
            try {
                lblBiaSach.setIcon(Convert.load(path, lblBiaSach.getSize().width, lblBiaSach.getSize().height));
            } catch (Exception e) {
                lblBiaSach.setIcon(new ImageIcon(""));
            }

        } else {
            lblBiaSach.setIcon(new ImageIcon(""));
        }
    }

    private void setFalseButton() {
        btnNamMuoiNghin.setEnabled(false);
        btnMotTramNghin.setEnabled(false);
        btnHaiTramNghin.setEnabled(false);
        btnNamTramNghin.setEnabled(false);
        btn0.setEnabled(false);
        btn1.setEnabled(false);
        btn2.setEnabled(false);
        btn3.setEnabled(false);
        btn4.setEnabled(false);
        btn5.setEnabled(false);
        btn6.setEnabled(false);
        btn7.setEnabled(false);
        btn8.setEnabled(false);
        btn9.setEnabled(false);
        btnXoaLui.setEnabled(false);
    }

    private void setTrueButton() {
        btnNamMuoiNghin.setEnabled(true);
        btnMotTramNghin.setEnabled(true);
        btnHaiTramNghin.setEnabled(true);
        btnNamTramNghin.setEnabled(true);
        btn0.setEnabled(true);
        btn1.setEnabled(true);
        btn2.setEnabled(true);
        btn3.setEnabled(true);
        btn4.setEnabled(true);
        btn5.setEnabled(true);
        btn6.setEnabled(true);
        btn7.setEnabled(true);
        btn8.setEnabled(true);
        btn9.setEnabled(true);
        btnXoaLui.setEnabled(true);
    }

    private void tinhTienDu() {
        Integer tongTien = Integer.parseInt(lblTongTien.getText());
        if (txtTienKhachDua.getText().isEmpty()) {
            txtTienTraLaiKhach.setText("");
        } else if (txtTienKhachDua.getText().equals("00")) {
            txtTienKhachDua.setText("");
            txtTienTraLaiKhach.setText("");
        } else {
            Integer tienKhachDua = Integer.parseInt(txtTienKhachDua.getText());
            Integer tienDu = tienKhachDua - tongTien;
            txtTienTraLaiKhach.setText(tienDu.toString());
        }
    }
}
