/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.qlth.frm;

import com.qlth.dao.NhaXuatBanDAO;
import com.qlth.obj.NhaXuatBan;
import com.qlth.util.Convert;
import com.qlth.util.Report;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.OK_CANCEL_OPTION;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hong Hiep
 */
public class FrmNhaXuatBan extends javax.swing.JFrame {
DefaultTableModel tableModel = new DefaultTableModel();
    /**
     * Creates new form FrmNhaXuatBan
     */
    public FrmNhaXuatBan() {
        initComponents();
        loadDuLieuLenLuoi();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNhaXuatBan = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        txtMaNhaXuatBan = new javax.swing.JTextField();
        txtTenNhaXuatBan = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        txtSoDienThoai = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnXoaTrang = new javax.swing.JButton();
        btnResetBang = new javax.swing.JButton();
        txtTimKiem = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        btnXuatExcel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Danh mục nhà xuất bản")));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        tblNhaXuatBan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblNhaXuatBan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNhaXuatBanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblNhaXuatBan);

        jPanel1.add(jScrollPane1);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin"));

        jPanel4.setLayout(new java.awt.GridLayout(4, 1));

        jLabel1.setText("Mã nhà xuất bản");
        jPanel4.add(jLabel1);

        jLabel2.setText("Tên nhà xuất bản");
        jPanel4.add(jLabel2);

        jLabel3.setText("Địa chỉ");
        jPanel4.add(jLabel3);

        jLabel4.setText("Số điện thoại");
        jPanel4.add(jLabel4);

        jPanel5.setLayout(new java.awt.GridLayout(4, 1));
        jPanel5.add(txtMaNhaXuatBan);
        jPanel5.add(txtTenNhaXuatBan);
        jPanel5.add(txtDiaChi);
        jPanel5.add(txtSoDienThoai);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Chức năng"));
        jPanel3.setLayout(new java.awt.GridLayout(5, 1));

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlth/img/20.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        jPanel3.add(btnThem);

        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlth/img/22.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        jPanel3.add(btnSua);

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlth/img/24.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        jPanel3.add(btnXoa);

        btnXoaTrang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlth/img/23.png"))); // NOI18N
        btnXoaTrang.setText("Xóa trắng");
        btnXoaTrang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaTrangActionPerformed(evt);
            }
        });
        jPanel3.add(btnXoaTrang);

        btnResetBang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlth/img/27.png"))); // NOI18N
        btnResetBang.setText("Reset bảng");
        btnResetBang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetBangActionPerformed(evt);
            }
        });
        jPanel3.add(btnResetBang);

        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlth/img/26.png"))); // NOI18N
        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        btnXuatExcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlth/img/34.png"))); // NOI18N
        btnXuatExcel.setText("Xuất excel");
        btnXuatExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatExcelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnXuatExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTimKiem))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnXuatExcel)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        if (txtMaNhaXuatBan.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Chưa nhập mã nhà xuất bản");
            return;
        }
        if (txtTenNhaXuatBan.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Chưa nhập tên nhà xuất bản");
            return;
        }

        NhaXuatBanDAO nhaXuatBanDAO = new NhaXuatBanDAO();
        //lấy giá trị nhập trên form truyền vào đôi tượng
        NhaXuatBan nxb = new NhaXuatBan();
        nxb.setMaNhaXuatBan(Convert.convertID(txtMaNhaXuatBan.getText()));
        nxb.setTenNhaXuatBan(Convert.convertName(txtTenNhaXuatBan.getText()));
        nxb.setDiaChi(txtDiaChi.getText());
        nxb.setSoDienThoai(txtSoDienThoai.getText());

        
        //thực hiện thêm vào DB
        boolean result = nhaXuatBanDAO.insert(nxb);
        //nếu thành công thì thông báo
        if (result) {
            JOptionPane.showMessageDialog(this, "Thêm sách thành công");
        }
        //reset form
        xoaTrang();
        //load lại dữ liệu lên lưới
        loadDuLieuLenLuoi();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        int row = tblNhaXuatBan.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn mục muốn sửa");
            return;
        }
        if (txtMaNhaXuatBan.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Chưa nhập mã nhà xuất bản");
            return;
        }
        if (txtTenNhaXuatBan.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Chưa nhập tên nhà xuất bản");
            return;
        }

        NhaXuatBanDAO nhaXuatBanDAO = new NhaXuatBanDAO();
        //lấy giá trị nhập trên form truyền vào đôi tượng
        NhaXuatBan nxb = new NhaXuatBan();
        nxb.setMaNhaXuatBanUpdate(Convert.convertID(txtMaNhaXuatBan.getText()));
        nxb.setTenNhaXuatBan(Convert.convertName(txtTenNhaXuatBan.getText()));
        nxb.setDiaChi(txtDiaChi.getText());
        nxb.setSoDienThoai(txtSoDienThoai.getText());

        nxb.setMaNhaXuatBan((String) tblNhaXuatBan.getValueAt(row, 0));
        //thực hiện thêm vào DB
        boolean result = nhaXuatBanDAO.update(nxb);
        //nếu thành công thì thông báo
        
        //reset form
        xoaTrang();
        //load lại dữ liệu lên lưới
        loadDuLieuLenLuoi();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        int row = tblNhaXuatBan.getSelectedRow();
        if (row >= 0) {
            int confirm = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa không?", "Thông báo", OK_CANCEL_OPTION);
            //Nếu chọn Yes
            if (confirm == JOptionPane.YES_OPTION) {
                //Lấy dòng được chọn

                //Lấy giá trị dòng được lấy cột đầu tiên => mã nhân viên
                String maNhaXuatBan = (String) tblNhaXuatBan.getValueAt(row, 0);
                NhaXuatBanDAO nhaXuatBanDAO = new NhaXuatBanDAO();
                NhaXuatBan nhaXuatBan = new NhaXuatBan(maNhaXuatBan);
                //thực hiện xóa vai trò
                boolean result = nhaXuatBanDAO.delete(nhaXuatBan);
                //thông báo
                if (result) {
                    JOptionPane.showMessageDialog(this, "Xóa sách thành công!");
                }
                //reset lại form nhập
                xoaTrang();
                //load lại dữ liệu lên lưới
                loadDuLieuLenLuoi();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Bạn chựa chọn mục muốn xóa");
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnXoaTrangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaTrangActionPerformed
        // TODO add your handling code here:
        xoaTrang();
    }//GEN-LAST:event_btnXoaTrangActionPerformed

    private void btnResetBangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetBangActionPerformed
        // TODO add your handling code here:
        loadDuLieuLenLuoi();
    }//GEN-LAST:event_btnResetBangActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        tableModel = new DefaultTableModel();
        //tạo cột
        tableModel.addColumn("Mã nhà xuất bản");
        tableModel.addColumn("Tên nhà xuất bản");
        tableModel.addColumn("Địa chỉ");
        tableModel.addColumn("Số điện thoại");
        
        
        NhaXuatBanDAO nhaXuatBanDAO = new NhaXuatBanDAO();
        //lấy ra thông tin tìm kiếm
        NhaXuatBan ls = new NhaXuatBan();
        ls.setMaNhaXuatBan(txtTimKiem.getText());
        ls.setTenNhaXuatBan(txtTimKiem.getText());
//        NhomKhachHang nhomKhachHang = (NhomKhachHang)cbbNhomKhachHang.getSelectedItem();
//        kh.setMaNhomKhachHang(nhomKhachHang!=null? nhomKhachHang.getMaNhomKhachHang():null);
        List<NhaXuatBan> nhaXuatBanList = nhaXuatBanDAO.search(ls);
        for (NhaXuatBan nhaXuatBan : nhaXuatBanList) {
            Vector vector = new Vector();
            vector.add(nhaXuatBan.getMaNhaXuatBan());
            vector.add(nhaXuatBan.getTenNhaXuatBan());
            vector.add(nhaXuatBan.getDiaChi());
            vector.add(nhaXuatBan.getSoDienThoai());
            
            //tạo hàng
            tableModel.addRow(vector);
        }
        //đưa dữ liệu từ model vào bảng
        tblNhaXuatBan.setModel(tableModel);
        tblNhaXuatBan.getColumnModel().getColumn(1).setPreferredWidth(200);
        tblNhaXuatBan.getColumnModel().getColumn(2).setPreferredWidth(200);
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void tblNhaXuatBanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNhaXuatBanMouseClicked
        // TODO add your handling code here:
        int row = tblNhaXuatBan.getSelectedRow();
        //lấy giá trị trên dòng được chọn cột thứ 0
        String maNhaXuatBan = (String) tblNhaXuatBan.getValueAt(row, 0);
        //lấy giá trị trên dòng được chọn cột thứ 1
        String tenNhaXuatBan = (String) tblNhaXuatBan.getValueAt(row, 1);
        //lấy giá trị trên dòng được chọn cột thứ 2
        String diaChi = (String) tblNhaXuatBan.getValueAt(row, 2);
        //lấy giá trị trên dòng được chọn cột thứ 2
        String soDienThoai = (String) tblNhaXuatBan.getValueAt(row, 3);
        //lấy giá trị trên dòng được chọn cột thứ 2
        
        txtMaNhaXuatBan.setText(maNhaXuatBan);
        txtTenNhaXuatBan.setText(tenNhaXuatBan);
        txtDiaChi.setText(diaChi);
        txtSoDienThoai.setText(soDienThoai);
    }//GEN-LAST:event_tblNhaXuatBanMouseClicked

    private void btnXuatExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatExcelActionPerformed
        Report report=new Report();
        report.xuatExcel(tableModel, this);
    }//GEN-LAST:event_btnXuatExcelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmNhaXuatBan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmNhaXuatBan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmNhaXuatBan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmNhaXuatBan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmNhaXuatBan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnResetBang;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXoaTrang;
    private javax.swing.JButton btnXuatExcel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblNhaXuatBan;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtMaNhaXuatBan;
    private javax.swing.JTextField txtSoDienThoai;
    private javax.swing.JTextField txtTenNhaXuatBan;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables

    private void loadDuLieuLenLuoi() {
        tableModel = new DefaultTableModel();
        //tạo cột
        tableModel.addColumn("Mã nhà xuất bản");
        tableModel.addColumn("Tên nhà xuất bản");
        tableModel.addColumn("Địa chỉ");
        tableModel.addColumn("Số điện thoại");
        

        NhaXuatBanDAO nhaXuatBanDAO = new NhaXuatBanDAO();
        //lấy ra toàn bộ vai trò
        List<NhaXuatBan> nhaXuatBanList = nhaXuatBanDAO.selectAll();
        for (NhaXuatBan nhaXuatBan : nhaXuatBanList) {
            Vector vector = new Vector();
            vector.add(nhaXuatBan.getMaNhaXuatBan());
            vector.add(nhaXuatBan.getTenNhaXuatBan());
            vector.add(nhaXuatBan.getDiaChi());
            vector.add(nhaXuatBan.getSoDienThoai());
            

            //tạo hàng
            tableModel.addRow(vector);
        }
        //đưa dữ liệu từ model vào bảng
        tblNhaXuatBan.setModel(tableModel);
        tblNhaXuatBan.getColumnModel().getColumn(1).setPreferredWidth(200);
        tblNhaXuatBan.getColumnModel().getColumn(2).setPreferredWidth(200);
    }

    private void xoaTrang() {
         txtDiaChi.setText("");
         txtMaNhaXuatBan.setText("");
         txtTenNhaXuatBan.setText("");
         txtSoDienThoai.setText("");
         txtTimKiem.setText("");
    }
}
